-- Seed expertise tags (~200 tags across domains)
-- These form the initial controlled vocabulary for the matching engine.

insert into public.expertise_tags (tag, domain, status) values
-- Agriculture
('crop management', 'agriculture', 'active'),
('soil health', 'agriculture', 'active'),
('irrigation systems', 'agriculture', 'active'),
('pest control', 'agriculture', 'active'),
('livestock management', 'agriculture', 'active'),
('organic farming', 'agriculture', 'active'),
('agricultural finance', 'agriculture', 'active'),
('post-harvest handling', 'agriculture', 'active'),
('agroforestry', 'agriculture', 'active'),
('dairy farming', 'agriculture', 'active'),
('aquaculture', 'agriculture', 'active'),
('seed selection', 'agriculture', 'active'),
('drought resilience', 'agriculture', 'active'),
('market access for farmers', 'agriculture', 'active'),
('climate-smart agriculture', 'agriculture', 'active'),

-- Business & Entrepreneurship
('business plan development', 'business', 'active'),
('market entry strategy', 'business', 'active'),
('cashflow management', 'business', 'active'),
('pricing strategy', 'business', 'active'),
('fundraising', 'business', 'active'),
('venture capital', 'business', 'active'),
('angel investing', 'business', 'active'),
('business model design', 'business', 'active'),
('customer acquisition', 'business', 'active'),
('sales strategy', 'business', 'active'),
('partnership development', 'business', 'active'),
('supply chain management', 'business', 'active'),
('franchise operations', 'business', 'active'),
('small business management', 'business', 'active'),
('social enterprise', 'business', 'active'),
('export and import', 'business', 'active'),
('retail operations', 'business', 'active'),
('e-commerce', 'business', 'active'),

-- Finance & Accounting
('financial planning', 'finance', 'active'),
('bookkeeping', 'finance', 'active'),
('tax compliance', 'finance', 'active'),
('debt restructuring', 'finance', 'active'),
('investment management', 'finance', 'active'),
('microfinance', 'finance', 'active'),
('insurance', 'finance', 'active'),
('budgeting', 'finance', 'active'),
('financial modelling', 'finance', 'active'),
('audit and assurance', 'finance', 'active'),
('corporate finance', 'finance', 'active'),
('personal finance', 'finance', 'active'),
('pension and retirement', 'finance', 'active'),
('grant writing', 'finance', 'active'),

-- Technology & Software
('web development', 'technology', 'active'),
('mobile app development', 'technology', 'active'),
('database design', 'technology', 'active'),
('cloud infrastructure', 'technology', 'active'),
('cybersecurity', 'technology', 'active'),
('data analytics', 'technology', 'active'),
('machine learning', 'technology', 'active'),
('devops', 'technology', 'active'),
('api design', 'technology', 'active'),
('system architecture', 'technology', 'active'),
('product management', 'technology', 'active'),
('ux design', 'technology', 'active'),
('it infrastructure', 'technology', 'active'),
('digital transformation', 'technology', 'active'),
('open source', 'technology', 'active'),

-- Education
('curriculum design', 'education', 'active'),
('classroom management', 'education', 'active'),
('special education', 'education', 'active'),
('early childhood education', 'education', 'active'),
('adult education', 'education', 'active'),
('education technology', 'education', 'active'),
('assessment design', 'education', 'active'),
('teacher training', 'education', 'active'),
('school leadership', 'education', 'active'),
('literacy', 'education', 'active'),
('numeracy', 'education', 'active'),
('vocational training', 'education', 'active'),
('higher education', 'education', 'active'),
('distance learning', 'education', 'active'),
('student wellbeing', 'education', 'active'),

-- Health & Medicine
('primary care', 'health', 'active'),
('maternal health', 'health', 'active'),
('child health', 'health', 'active'),
('mental health', 'health', 'active'),
('nutrition', 'health', 'active'),
('public health', 'health', 'active'),
('infectious disease', 'health', 'active'),
('chronic disease management', 'health', 'active'),
('community health', 'health', 'active'),
('health systems', 'health', 'active'),
('pharmacy', 'health', 'active'),
('physiotherapy', 'health', 'active'),
('nursing', 'health', 'active'),
('traditional medicine', 'health', 'active'),
('health education', 'health', 'active'),

-- Legal
('contract law', 'legal', 'active'),
('employment law', 'legal', 'active'),
('intellectual property', 'legal', 'active'),
('company formation', 'legal', 'active'),
('regulatory compliance', 'legal', 'active'),
('dispute resolution', 'legal', 'active'),
('family law', 'legal', 'active'),
('land and property law', 'legal', 'active'),
('immigration law', 'legal', 'active'),
('consumer rights', 'legal', 'active'),
('data protection', 'legal', 'active'),
('tax law', 'legal', 'active'),
('non-profit law', 'legal', 'active'),

-- Engineering & Construction
('civil engineering', 'engineering', 'active'),
('structural engineering', 'engineering', 'active'),
('electrical engineering', 'engineering', 'active'),
('mechanical engineering', 'engineering', 'active'),
('construction management', 'engineering', 'active'),
('project management', 'engineering', 'active'),
('water and sanitation', 'engineering', 'active'),
('renewable energy', 'engineering', 'active'),
('building design', 'engineering', 'active'),
('quality assurance', 'engineering', 'active'),
('industrial engineering', 'engineering', 'active'),
('environmental engineering', 'engineering', 'active'),

-- Marketing & Communications
('brand strategy', 'marketing', 'active'),
('content marketing', 'marketing', 'active'),
('social media marketing', 'marketing', 'active'),
('seo', 'marketing', 'active'),
('public relations', 'marketing', 'active'),
('advertising', 'marketing', 'active'),
('market research', 'marketing', 'active'),
('copywriting', 'marketing', 'active'),
('email marketing', 'marketing', 'active'),
('event marketing', 'marketing', 'active'),
('influencer marketing', 'marketing', 'active'),
('positioning', 'marketing', 'active'),

-- Human Resources & Management
('recruitment', 'management', 'active'),
('performance management', 'management', 'active'),
('team leadership', 'management', 'active'),
('organisational design', 'management', 'active'),
('change management', 'management', 'active'),
('conflict resolution', 'management', 'active'),
('employee wellbeing', 'management', 'active'),
('training and development', 'management', 'active'),
('compensation and benefits', 'management', 'active'),
('remote team management', 'management', 'active'),
('corporate governance', 'management', 'active'),
('succession planning', 'management', 'active'),

-- Environment & Sustainability
('climate change adaptation', 'environment', 'active'),
('waste management', 'environment', 'active'),
('conservation', 'environment', 'active'),
('sustainable development', 'environment', 'active'),
('carbon accounting', 'environment', 'active'),
('environmental impact assessment', 'environment', 'active'),
('circular economy', 'environment', 'active'),
('biodiversity', 'environment', 'active'),
('clean energy transition', 'environment', 'active'),
('water resource management', 'environment', 'active'),

-- Non-profit & Development
('ngo management', 'development', 'active'),
('programme design', 'development', 'active'),
('monitoring and evaluation', 'development', 'active'),
('community development', 'development', 'active'),
('humanitarian response', 'development', 'active'),
('donor relations', 'development', 'active'),
('impact measurement', 'development', 'active'),
('capacity building', 'development', 'active'),
('advocacy', 'development', 'active'),
('gender equality', 'development', 'active'),
('youth development', 'development', 'active'),
('refugee support', 'development', 'active'),

-- Personal Development
('career transition', 'personal', 'active'),
('public speaking', 'personal', 'active'),
('negotiation', 'personal', 'active'),
('time management', 'personal', 'active'),
('mentoring', 'personal', 'active'),
('coaching', 'personal', 'active'),
('writing', 'personal', 'active'),
('networking', 'personal', 'active'),
('interview preparation', 'personal', 'active'),
('freelancing', 'personal', 'active'),

-- Creative & Media
('graphic design', 'creative', 'active'),
('video production', 'creative', 'active'),
('photography', 'creative', 'active'),
('music production', 'creative', 'active'),
('journalism', 'creative', 'active'),
('film making', 'creative', 'active'),
('animation', 'creative', 'active'),
('podcasting', 'creative', 'active'),
('publishing', 'creative', 'active'),

-- Trades & Practical Skills
('plumbing', 'trades', 'active'),
('carpentry', 'trades', 'active'),
('welding', 'trades', 'active'),
('automotive repair', 'trades', 'active'),
('electrical installation', 'trades', 'active'),
('tailoring', 'trades', 'active'),
('food processing', 'trades', 'active'),
('metalwork', 'trades', 'active'),
('masonry', 'trades', 'active')

on conflict (tag) do nothing;
